version: "{build}"

clone_depth: 5

skip_tags: true

branches:
  except:
    - /^(osx|linux|jar|windows)$/

environment:
  ssh_secret:
    secure: rSGxPYhT1WpkysdoBRSgj65HwEu3ULsFCfOoP7zJ/YbaVihhK8RfjaHcHQi50JH0
  PYTHON: C:\Python36-x64
  CHECKER_PY: .\checker.py
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12
    - JAVA_HOME: C:\Program Files\Java\jdk13

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - java -version
  - python --version
  - python %CHECKER_PY% update
  - appveyor-retry python %CHECKER_PY% dldeps

build_script:
  - python %CHECKER_PY% build

test_script:
  - python %CHECKER_PY% jar
  - java -jar .\build\dist\vnu.jar .\build\dist\index.html
  - java -jar .\build\dist\vnu.jar .\site\nu-about.html
  - python %CHECKER_PY% runtime-image
  - python %CHECKER_PY% war
  - python %CHECKER_PY% check
  - python %CHECKER_PY% test
  - bash -lc 'for file in build/dist/*.zip*; do touch $file.asc; done' # FIXME hack just to ensure the .asc files get uploaded during deploy

cache:
  # cache the dependencies folder, and invalidate the cache
  # if any of the files right of the arrow change
  - 'dependencies -> .appveyor.yml,%CHECKER_PY%,build\build.py,build\build.xml'

before_deploy:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt resources\ssh_appveyor.enc -out resources\ssh_appveyor -secret %ssh_secret%
  - chmod 600 resources\ssh_appveyor
  - cat resources\ssh_known_hosts >> %userprofile%\.ssh\known_hosts
  - chmod 600 %userprofile%\.ssh\known_hosts
  - git config --local user.name "AppVeyor"
  - git config --local user.email "mike@w3.org"
  - bash -lc "GIT_SSH_COMMAND='ssh -i resources/ssh_appveyor' git push --delete git@github.com:validator/validator.git windows || true"
  - git tag -m windows -f windows

artifacts:
  - path: 'build\dist\*.zip*'
    name: RuntimeImageArtifacts

deploy:
  tag: windows
  provider: GitHub
  auth_token:
    secure: kQDmkxCMEYfOefd3yGIfOTLL8e+w512Mv7tojXIVwH7Dgv0xx0n0mfdQXRFdKbXE
  artifact: RuntimeImageArtifacts
  draft: false
  prerelease: true
  force_update: true
  on:
    JAVA_HOME: C:\Program Files\Java\jdk11
