version: "{build}"

clone_depth: 5

branches:
  except:
    - /^(osx|linux|jar|windows)$/

environment:
  ssh_secret:
    secure: rSGxPYhT1WpkysdoBRSgj65HwEu3ULsFCfOoP7zJ/YbaVihhK8RfjaHcHQi50JH0
  PYTHON: C:\Python36-x64
  BUILD_PY: .\build\build.py
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - java -version
  - python --version
  - python %BUILD_PY% update-shallow
  - appveyor-retry python %BUILD_PY% dldeps

build_script:
  - python %BUILD_PY% build

test_script:
  - python %BUILD_PY% check
  - python %BUILD_PY% test
  - python %BUILD_PY% jar
  - java -jar .\build\dist\vnu.jar .\build\dist\index.html
  - java -jar .\build\dist\vnu.jar .\site\nu-about.html
  - python %BUILD_PY% war

cache:
  # cache the dependencies folder, and invalidate the cache
  # if any of the files right of the arrow change
  - 'dependencies -> .appveyor.yml,%BUILD_PY%,build\build.xml'

artifacts:
  - path: '**\*.zip*'
    name: RuntimeImageArtifacts

before_deploy:
  - cinst -y openssh
  - refreshenv
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt appveyor_key.enc -secret %ssh_secret%
  - chmod 600 appveyor_key
  - cat known_hosts >> %userprofile%\.ssh\known_hosts
  - chmod 600 %userprofile%\.ssh\known_hosts
  - eval $(ssh-agent -s)
  - ssh-add appveyor_key
  - git config --local user.name "Travis CI"
  - git config --local user.email "mike@w3.org"
  - git push --delete git@github.com:validator/validator.git windows || true
  - git tag -m windows -f windows

deploy:
  tag: windows
  provider: GitHub
  auth_token:
    secure: kQDmkxCMEYfOefd3yGIfOTLL8e+w512Mv7tojXIVwH7Dgv0xx0n0mfdQXRFdKbXE
  artifact: RuntimeImageArtifacts
  draft: false
  prerelease: true
  force_update: true
  on:
    JAVA_HOME: C:\Program Files\Java\jdk11
