language: java

script:
  - git clone https://github.com/validator/build.git build
  - python ./build/build.py checkout
  - python ./build/build.py dldeps
  - python ./build/build.py build; python ./build/build.py build
  - python ./build/build.py check
  - echo "test" | python ./build/build.py jar
  - python ./build/build.py test
  - java -jar ./build/vnu/vnu.jar ./build/vnu/index.html
