language: java

script:
  - python ./build/build.py dldeps
  - python ./build/build.py build
  - python ./build/build.py check
  - python ./build/build.py test
  - echo "test" | python ./build/build.py jar
  - java -jar ./build/dist/vnu.jar ./build/dist/index.html
  - java -jar ./build/dist/vnu.jar ./site/nu-about.html
  - jar xf ./build/dist/vnu.jar && file nu/validator/client/SimpleCommandLineValidator.class | grep "version 50.0"
  - echo "test" | python ./build/build.py war
  - jar xf ./build/dist/vnu.war && file WEB-INF/classes/nu/validator/servlet/VerifierServlet.class | grep "version 50.0"
