language: java
deploy:
  api_key:
    secure: ayJRuase0HQbdrGmXd+FiX/JI0BUdIP6L/ovLLvIZSwaN+YopJaVkFSviZ5ce7NlAeTLeCjPErgjEPIN3Pok0ujLosshaL1U6KHwCCvnQNC1Sy3s0mQcDyv9aDeQ/ln7wQR6/Tb72BZbyr1nYmhDHKnRq/s1wMYjINGsBmt9aEg=
script:
- python ./build/build.py dldeps
- python ./build/build.py build
- python ./build/build.py check
- python ./build/build.py test
- echo "test" | python ./build/build.py jar
- java -jar ./build/dist/vnu.jar ./build/dist/index.html
- java -jar ./build/dist/vnu.jar ./site/nu-about.html
- jar xf ./build/dist/vnu.jar && file nu/validator/client/SimpleCommandLineValidator.class
  | grep "version 50.0"
- echo "test" | python ./build/build.py war
- jar xf ./build/dist/vnu.war && file WEB-INF/classes/nu/validator/servlet/VerifierServlet.class
  | grep "version 50.0"
- apt-get install tomcat8
- cp ./build/dist/vnu.war /var/lib/tomcat7/webapps
- sleep 10
- curl http://localhost:8080/?out=gnu&doc=data:text/html;charset=utf-8,<!doctype%20html><meta%20charset=utf-8><title>test</title>
  #- wget -qO- https://toolbelt.heroku.com/install.sh | sh
  #- /usr/local/heroku/bin/heroku plugins:install https://github.com/heroku/heroku-deploy
  #- HEROKU_API_KEY=ayJRuase0HQbdrGmXd+FiX/JI0BUdIP6L/ovLLvIZSwaN+YopJaVkFSviZ5ce7NlAeTLeCjPErgjEPIN3Pok0ujLosshaL1U6KHwCCvnQNC1Sy3s0mQcDyv9aDeQ/ln7wQR6/Tb72BZbyr1nYmhDHKnRq/s1wMYjINGsBmt9aEg= /usr/local/heroku/bin/heroku deploy:war --war ./build/dist/vnu.war --app vnu
