name: Push a new Docker image

on:
  create:
    tags-ignore: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      uses: ./.github/actions/docker-push
